### ISSUE TITLE
[Bug] Default rgb animation

### ISSUE THREAD

**Issue by dexter93** [SonixQMK/qmk_firmware#81]
Default RGB animation is rainbow

However, when the usb driver kicks in, it switches to red breathing. You can observe this behavior by unplugging the keyboard and switching to battery ( bluetooth) mode.

Need to figure out this inconsistency and see if it is our code, or QMK upstream behavior

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by dexter93** [comment]
Bug traces back to [this](https://github.com/SonixQMK/qmk_firmware/commit/71a53f4070d5db020ddc0623a4309d62986651f2#)

We do not handle rgb matrix shutdown/restart when we boot up, so the animation stays the same if sleep led is enabled

**Comment by dexter93** [comment]
Bug fixed with https://github.com/SonixQMK/qmk_firmware/pull/150

**Comment by Coding-Kiwi** [comment]
I'm at the latest version with the changes of #150 merged in, I can still reproduce the issue on Win10 with a keychron k4v2 iso rgb

process:

1) switch the animation to rgb spiral mode
2) power down pc -> rgb is off
3) power on pc -> rgb is in the saved mode (rgb spiral), but then switches to breathing mode by itself

I also tried the changes suggested [here](https://github.com/SonixQMK/qmk_firmware/issues/80#issuecomment-948231491)
